### ISSUE TITLE
CentOS Installation part

### ISSUE THREAD

**Issue by sebthebert** [sebthebert/ansible-role-octopussy#1]

**Comment by ghost** [comment]
I'll start with this one!

**Comment by sebthebert** [comment]
@thegreyelephant 
I'm actually working on the CentOS part and I will probably have finished before the week-end.
You could then use what I did for CentOS and adapt it for Fedora ?

**Comment by ghost** [comment]
@sebthebert that sounds like a great idea, thanks!
