### ISSUE TITLE
Fedora Installation part

### ISSUE THREAD

**Issue by sebthebert** [sebthebert/ansible-role-octopussy#2]

**Comment by ghost** [comment]
What needs to be done for this one?

**Comment by sebthebert** [comment]
@thegreyelephant 
Basically write [this installation](https://github.com/sebthebert/Octopussy_Documentation/blob/master/01_Installation.md#fedora-installation) with Ansible

**Comment by ghost** [comment]
@sebthebert I've fairly new to Ansible but I am a long time Linux user. Looks like a fun challenge!

**Comment by sebthebert** [comment]
@thegreyelephant I've just released a working version for CentOS 6 & 7. 
You can use it for your Fedora part.

**Comment by ghost** [comment]
Great - thanks!

**Comment by sebthebert** [comment]
@thegreyelephant Are you close to Pull Request for the Fedora installation ?

**Comment by SakshamSaxena97** [comment]
@sebthebert I m interested in this, you need the fedora installation through ansible.... right?

**Comment by sebthebert** [comment]
@SakshamSaxena97 Yes, that's right.

**Comment by sebthebert** [comment]
No news, so I take it.

**Comment by sebthebert** [comment]
Closed by PR #9
